source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'WRPDFReader_Example' do
  pod 'WRPDFReader', :path => '../'
  pod 'WRPDFModel', '~> 0.0.2'
  pod 'WRTextKit', '~> 1.3.8'
end
